management/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('management.views',

    url(r'^manage/organization/$', 'view_managing_organization', name='view_managing_organization'),

    url(r'^manage/users/$', 'view_managing_users', name='view_managing_users'),
    url(r'^manage/users/section/$', 'view_managing_section_users', name='view_managing_section_users'),
    url(r'^manage/users/project/$', 'view_managing_project_users', name='view_managing_project_users'),

    url(r'^manage/users/add/$', 'add_managing_user', name='add_managing_user'),
    url(r'^manage/users/(?P<user_id>\d+)/add/responsibility/$', 'add_managing_user_responsibility', name='add_managing_user_responsibility'),
    url(r'^manage/users/(?P<user_id>\d+)/password/$', 'view_managing_user_password', name='view_managing_user_password'),

    url(r'^manage/users/(?P<user_id>\d+)/edit/$', 'edit_managing_user', name='edit_managing_user'),

    url(r'^manage/users/(?P<user_id>\d+)/edit/projects/$', 'edit_managing_user_projects', name='edit_managing_user_projects'),
    url(r'^ajax/remove_managing_project/$', 'ajax_remove_managing_project', name='ajax_remove_managing_project'),

    url(r'^manage/users/(?P<user_id>\d+)/deactivate/$', 'deactivate_managing_user', name='deactivate_managing_user'),
    
    
    url(r'^manage/users/import/$', 'import_managing_users', name='import_managing_users'),

    url(r'^manage/import/$', 'import_from_gms', name='import_from_gms'),
    url(r'^manage/import/details/$', 'view_manage_import_details', name='view_manage_import_details'),

)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('accounts.urls')),
    url(r'^', include('budget.urls')),
    url(r'^', include('domain.urls')),
    url(r'^', include('management.urls')),
    url(r'^', include('report.urls')),

    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page':'/accounts/login/'},name='auth_logout'),
    url(r'^accounts/password_reset/$', 'django.contrib.auth.views.password_reset', name='auth_password_reset'),
    url(r'^accounts/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='auth_password_reset_done'),
    url(r'^accounts/reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', name='auth_password_reset_confirm'),
    url(r'^accounts/reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='auth_password_reset_complete'),

    (r'^$', RedirectView.as_view(url='dashboard/')),

    url(r'^admin/', include(admin.site.urls)),
)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db import models
from django.template.loader import render_to_string

from common.utilities import make_random_user_password, generate_md5_base64

class Role(models.Model):
    code = models.CharField(max_length=300, db_index=True, unique=True)
    name = models.CharField(max_length=300)

    def __unicode__(self):
        return self.name

class UserProfileManager(models.Manager):

    def create_user(self, email, first_name, last_name, primary_role, password='', is_finished_register=False):
        username = generate_md5_base64(email)

        if not password:
            random_password = make_random_user_password()
            password = random_password
        else:
            random_password = ''

        user = User.objects.create_user(username, '', password)

        return UserProfile.objects.create(
            user=user,
            email=email,
            first_name=first_name,
            last_name=last_name,
            random_password=random_password,
            primary_role=primary_role,
            is_finished_register=is_finished_register
        )

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    email = models.CharField(max_length=254, unique=True)
    first_name = models.CharField(max_length=300)
    last_name = models.CharField(max_length=300)
    random_password = models.CharField(max_length=30, null=True, blank=True)
    primary_role = models.ForeignKey(Role)
    is_finished_register = models.BooleanField(default=False)

    def __unicode__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def save(self, *args, **kwargs):
        """ Update username hash in User object """
        self.user.username = generate_md5_base64(self.email)
        self.user.save()

        super(UserProfile, self).save(*args, **kwargs)

    objects = UserProfileManager()

    def get_fullname(self):
        return '%s %s' % (self.first_name, self.last_name)
    
    def is_section_staff(self):
        return self.primary_role.code in ('section_manager', 'section_assistant')
    
    def is_project_manager(self):
        return self.primary_role.code == 'project_manager'
    
    def is_in_section(self, section):
        return UserSection.objects.filter(user=self.user, section=section).exists()
    
    def is_manage_project(self, project, role=None):
        if role == 'pm':
            return ProjectManager.objects.filter(user=self.user, project=project).exists()
        
        elif role == 'assistant':
            return ProjectResponsibility.objects.filter(user=self.user, project=project).exists()

        return ProjectManager.objects.filter(user=self.user, project=project).exists() or ProjectResponsibility.objects.filter(user=self.user, project=project).exists()
    
    def send_password_email(self):
        email_render_dict = {'user_profile':self, 'settings':settings}
        email_subject = render_to_string('email/create_user_subject.txt', email_render_dict)
        email_message = render_to_string('email/create_user_message.txt', email_render_dict)
        
        send_mail(email_subject, email_message, settings.SYSTEM_NOREPLY_EMAIL, [self.user.email])

class UserSection(models.Model): # for section manager, section assistant
    user = models.ForeignKey(User)
    section = models.ForeignKey('domain.Section')
    is_active = models.BooleanField(default=True)

class ProjectResponsibility(models.Model): # for section assistant
    user = models.ForeignKey(User)
    project = models.ForeignKey('domain.Project')
    is_active = models.BooleanField(default=True)

class ProjectManager(models.Model): # for project manager
    user = models.ForeignKey(User)
    project = models.ForeignKey('domain.Project')
    is_active = models.BooleanField(default=True)

domain/models.py
# -*- encoding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models

from accounts.models import ProjectManager

class Section(models.Model):
    ref_no = models.CharField(max_length=10)
    prefix = models.CharField(max_length=50)
    name = models.CharField(max_length=500)
    long_abbr_name = models.CharField(max_length=100)
    short_abbr_name = models.CharField(max_length=100)
    order_number = models.IntegerField(default=0)

    def __unicode__(self):
        return self.short_abbr_name

class Project(models.Model):
    section = models.ForeignKey(Section)
    ref_no = models.CharField(max_length=100, unique=True)
    contract_no = models.CharField(max_length=100, null=True, unique=True)
    prefix = models.CharField(max_length=50, blank=True)
    name = models.CharField(max_length=1000)
    abbr_name = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    manager_name = models.CharField(max_length=300, blank=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    project_type = models.IntegerField(default=0) # Not use yet
    status = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User)

    class Meta:
        ordering = ['ref_no']
    
    def __unicode__(self):
        return self.ref_no
    
    def is_active(self):
        return self.status in (u'อนุมัติ', u'รอปิดโครงการ')

    def managers(self):
        return ProjectManager.objects.filter(project=self, is_active=True)

## IMPORT FROM GMS ##

class ImportGMS(models.Model):
    started = models.DateTimeField(auto_now_add=True)
    finished = models.DateTimeField()
    imported_by = models.ForeignKey(User)
    created_projects = models.IntegerField(default=0)
    updated_projects = models.IntegerField(default=0)
    notfound_projects = models.IntegerField(default=0)
    created_budgets = models.IntegerField(default=0)

class ImportGMSProjects(models.Model):
    job = models.ForeignKey(ImportGMS)
    project_ref_no = models.CharField(max_length=100)
    is_found = models.BooleanField()
    is_created = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)

management/models.py
from django.db import models

# Create your models here.

management/forms.py
# -*- encoding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User

from common.forms import StrippedCharField
from common.utilities import split_filename

from accounts.models import UserProfile
from domain.models import Section, Project

class AddUserForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'span6'}))
    first_name = StrippedCharField(max_length=300, widget=forms.TextInput(attrs={'class':'span5'}))
    last_name = StrippedCharField(max_length=300, widget=forms.TextInput(attrs={'class':'span5'}))
    primary_role = forms.ChoiceField(choices=(('section_manager', 'ผู้อำนวยการสำนัก'), ('section_assistant', 'ผู้ประสานงานสำนัก'), ('project_manager', 'ผู้รับผิดชอบโครงการ')))

class AddSectionUserResponsibilityForm(forms.Form):
    section = forms.ModelChoiceField(queryset=Section.objects.all(), empty_label=None)

class AddProjectManagerResponsibilityForm(forms.Form):
    project_ref_no = StrippedCharField(max_length=100, widget=forms.TextInput(attrs={'class':'span3'}))

    def clean_project_ref_no(self):
        project_ref_no = self.cleaned_data['project_ref_no']

        try:
            project = Project.objects.get(ref_no=project_ref_no)
        except Project.DoesNotExist:
            raise forms.ValidationError('รหัสโครงการไม่ถูกต้อง')

        return project_ref_no

class ImportUserForm(forms.Form):
    user_csv = forms.FileField()

    def clean_user_csv(self):
        user_csv = self.cleaned_data.get('user_csv')

        if user_csv and split_filename(user_csv.name)[1].lower() != 'csv':
            raise forms.ValidationError('ระบบอ่านได้เฉพาะไฟล์นามสกุล CSV เท่านั้น')
        
        return user_csv

class EditSectionUserForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'span6'}))
    first_name = StrippedCharField(max_length=300, widget=forms.TextInput(attrs={'class':'span5'}))
    last_name = StrippedCharField(max_length=300, widget=forms.TextInput(attrs={'class':'span5'}))
    section = forms.ModelChoiceField(queryset=Section.objects.all(), empty_label='')

    def __init__(self, user, *args, **kwargs):
        self.user = user
        forms.Form.__init__(self, *args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get('email', '')

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        else:
            if user.id != self.user.id:
                raise forms.ValidationError('อีเมลนี้ซ้ำกับผู้ใช้คนอื่นในระบบ')

class EditProjectUserForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'span6'}))
    first_name = StrippedCharField(max_length=300, widget=forms.TextInput(attrs={'class':'span5'}))
    last_name = StrippedCharField(max_length=300, widget=forms.TextInput(attrs={'class':'span5'}))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        forms.Form.__init__(self, *args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get('email', '')

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        else:
            if user.id != self.user.id:
                raise forms.ValidationError('อีเมลนี้ซ้ำกับผู้ใช้คนอื่นในระบบ')

templates/management/manage_import.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}ดึงข้อมูลจาก GMS{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'management/snippets/admin_tabs.html' with active_menu='import' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <form method="POST" action=".">
    {% csrf_token %}
    <div class="page_actions"><button type="submit" class="btn btn-primary">เริ่มต้นดึงข้อมูล</button></div>
  </form>

<!--
    <div class="last_import">
        <h2>ผลลัพธ์การดึงข้อมูลครั้งล่าสุด</h2>
        <ul>
            <li>สร้างโครงการ 10 โครงการ</li>
        </ul>
        <div class="view_details"><a href="{% url view_manage_import_details %}">ดูผลลัพธ์อย่างละเอียด</a></div>
    </div>
-->

</div>
{% endblock %}

templates/management/manage_org.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}จัดการผู้ใช้{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'management/snippets/admin_tabs.html' with active_menu='organization' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
    <h2>สำนัก / ฝ่าย</h2>
    <ul class="org">
        {% for section in sections %}
        <li><a href="{% url view_section section.ref_no %}">{{section.short_abbr_name}} - {{section.name}}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/management/manage_users_add.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}เพิ่มผู้ใช้ระบบ{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'management/snippets/admin_tabs.html' with active_menu='user' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_managing_users %}">จัดการผู้ใช้</a> <span class="divider">/</span></li>
    <li class="active">เพิ่มผู้ใช้ระบบ</li>
  </ul>
  <h2>เพิ่มผู้ใช้ระบบ</h2>

  <ul class="nav nav-tabs">
    <li class="active"><a href="{% url add_managing_user %}">กรอกจากแบบฟอร์ม</a></li>
    <li><a href="{% url import_managing_users %}">ดึงจากไฟล์ CSV</a></li>
  </ul>

  <form method="POST" action="." class="form-horizontal">
    {% csrf_token %}
    {{form.non_field_errors}}

    <div class="control-group"><label for="id_email" class="control-label">อีเมล</label><div class="controls">{{form.email}}<p class="help-block">ใช้สำหรับการเข้าสู่ระบบ และการแจ้งเตือนต่างๆ</p>{{form.email.errors}}</div></div>
    <div class="control-group"><label for="id_first_name" class="control-label">ชื่อ</label><div class="controls">{{form.first_name}}{{form.first_name.errors}}</div></div>
    <div class="control-group"><label for="id_last_name" class="control-label">นามสกุล</label><div class="controls">{{form.last_name}}{{form.last_name.errors}}</div></div>
    <div class="control-group"><label for="id_primary_role" class="control-label">ประเภทผู้ใช้</label><div class="controls">{{form.primary_role}}{{form.primary_role.errors}}</div></div>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary">บันทึกและไปขั้นตอนต่อไป</button>
      <button type="reset" class="btn">ล้างข้อมูล</button>
    </div>
  </form>


</div>
{% endblock %}

templates/management/manage_users_add_project_manager.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}เพิ่มผู้ใช้ระบบ{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'management/snippets/admin_tabs.html' with active_menu='user' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_managing_users %}">จัดการผู้ใช้</a> <span class="divider">/</span></li>
    <li class="active">เพิ่มผู้ใช้ระบบ</li>
  </ul>
  <h2>โครงการที่รับผิดชอบ</h2>

  <form method="POST" action="." class="form-horizontal">
    {% csrf_token %}
    {{form.non_field_errors}}

    <div class="control-group"><label for="id_project_ref_no" class="control-label">รหัสโครงการ</label><div class="controls">{{form.project_ref_no}}{{form.project_ref_no.errors}}</div></div>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary" name="submit_button">บันทึกข้อมูล</button>
      <button type="submit" class="btn" name="submit_continue_button">บันทึกข้อมูล และกรอกรหัสโครงการเพิ่มเติม</button>
      <button type="reset" class="btn">ล้างข้อมูล</button>
    </div>
  </form>
</div>
{% endblock %}

templates/management/manage_users_add_section_user.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}เพิ่มผู้ใช้ระบบ{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'management/snippets/admin_tabs.html' with active_menu='user' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_managing_users %}">จัดการผู้ใช้</a> <span class="divider">/</span></li>
    <li class="active">เพิ่มผู้ใช้ระบบ</li>
  </ul>
  <h2>สำนักที่สังกัด</h2>

  <form method="POST" action="." class="form-horizontal">
    {% csrf_token %}
    {{form.non_field_errors}}

    <div class="control-group"><label for="id_section" class="control-label">สำนักที่สังกัด</label><div class="controls">{{form.section}}{{form.section.errors}}</div></div>
    
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">เพิ่มผู้ใช้ระบบ</button>
      <button type="reset" class="btn">ล้างข้อมูล</button>
    </div>
  </form>
</div>
{% endblock %}

templates/management/manage_users_edit_project_user.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}แก้ไขผู้ใช้{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'management/snippets/admin_tabs.html' with active_menu='user' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_managing_project_users %}">จัดการผู้ใช้</a> <span class="divider">/</span></li>
    <li class="active">แก้ไขผู้ใช้</li>
  </ul>
  <h2>แก้ไขผู้ใช้ {{this_user.get_profile.get_fullname}}</h2>

  <ul class="nav nav-tabs">
    <li class="active"><a href="{% url edit_managing_user this_user.id %}">ข้อมูลผู้ใช้</a></li>
    <li><a href="{% url edit_managing_user_projects this_user.id %}">โครงการที่รับผิดชอบ</a></li>
  </ul>

  <form method="POST" action="." class="form-horizontal">
    {% csrf_token %}
    {{form.non_field_errors}}

    <div class="control-group"><label for="id_email" class="control-label">อีเมล</label><div class="controls">{{form.email}}<p class="help-block">ใช้สำหรับการเข้าสู่ระบบ และการแจ้งเตือนต่างๆ</p>{{form.email.errors}}</div></div>
    <div class="control-group"><label for="id_first_name" class="control-label">ชื่อ</label><div class="controls">{{form.first_name}}{{form.first_name.errors}}</div></div>
    <div class="control-group"><label for="id_last_name" class="control-label">นามสกุล</label><div class="controls">{{form.last_name}}{{form.last_name.errors}}</div></div>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary">บันทึกข้อมูล</button>
      <button type="reset" class="btn">ล้างข้อมูล</button>
    </div>
  </form>
</div>
{% endblock %}

templates/management/manage_users_edit_section_user.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}แก้ไขผู้ใช้{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'management/snippets/admin_tabs.html' with active_menu='user' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_managing_section_users %}">จัดการผู้ใช้</a> <span class="divider">/</span></li>
    <li class="active">แก้ไขผู้ใช้</li>
  </ul>
  <h2>แก้ไขผู้ใช้ {{this_user.get_profile.get_fullname}}</h2>

  <form method="POST" action="." class="form-horizontal">
    {% csrf_token %}
    {{form.non_field_errors}}

    <div class="control-group"><label for="id_email" class="control-label">อีเมล</label><div class="controls">{{form.email}}<p class="help-block">ใช้สำหรับการเข้าสู่ระบบ และการแจ้งเตือนต่างๆ</p>{{form.email.errors}}</div></div>
    <div class="control-group"><label for="id_first_name" class="control-label">ชื่อ</label><div class="controls">{{form.first_name}}{{form.first_name.errors}}</div></div>
    <div class="control-group"><label for="id_last_name" class="control-label">นามสกุล</label><div class="controls">{{form.last_name}}{{form.last_name.errors}}</div></div>
    <div class="control-group"><label for="id_section" class="control-label">สำนักที่สังกัด</label><div class="controls">{{form.section}}{{form.section.errors}}</div></div>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary">บันทึกข้อมูล</button>
      <button type="reset" class="btn">ล้างข้อมูล</button>
    </div>
  </form>

</div>
{% endblock %}

templates/management/manage_users_import.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}เพิ่มผู้ใช้ระบบ{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'management/snippets/admin_tabs.html' with active_menu='user' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_managing_users %}">จัดการผู้ใช้</a> <span class="divider">/</span></li>
    <li class="active">เพิ่มผู้ใช้ระบบ</li>
  </ul>
  <h2>เพิ่มผู้ใช้ระบบ</h2>

  <ul class="nav nav-tabs">
    <li><a href="{% url add_managing_user %}">กรอกฟอร์มผู้ใช้</a></li>
    <li class="active"><a href="{% url import_managing_users %}">ดึงจากไฟล์ CSV</a></li>
  </ul>

  {% if not import_result %}

    <form method="POST" action="." enctype="multipart/form-data" class="form-horizontal">
      {% csrf_token %}
      {{form.non_field_errors}}

      <div class="control-group"><label for="id_user_csv" class="control-label">ไฟล์ CSV</label><div class="controls">{{form.user_csv}}{{form.user_csv.errors}}<p class="help-block">ดาวน์โหลดไฟล์สำหรับกรอกข้อมูล - <a href="{{STATIC_URL}}misc/import_users_template.xls">ดาวน์โหลดไฟล์ Excel</a></p></div></div>

      <div class="form-actions">
        <button type="submit" class="btn btn-primary">เพิ่มผู้ใช้ระบบ</button>
        <button type="reset" class="btn">ล้างข้อมูล</button>
      </div>
    </form>

  {% else %}

    <div class="page_actions"><a href="{% url view_managing_users %}" class="btn">กลับไปหน้าจัดการผู้ใช้</a></div>
    <h3>ผลลัพธ์การดึงไฟล์ CSV</h3>

    <table class="table table-bordered import_users_result_table">
      <thead>
        <tr>
          <th>#</th>
          <th>อีเมล / ชื่อผู้ใช้</th>
          <th>กลุ่มผู้ใช้</th>
          <th>ผลลัพธ์</th>
        </tr>
      </thead>
      <tbody>
        {% for result in import_result %}

          {% if result.status == 'email-invalid' %}<tr class="error"><td>{{forloop.counter}}</td><td class="user">{{result.email}}</td><td></td><td>อีเมลไม่ถูกต้อง</td></tr>{% endif %}
          {% if result.status == 'firstname-missing' %}<tr class="error"><td>{{forloop.counter}}</td><td class="user">{{result.email}}</td><td></td><td>ขาดข้อมูลชื่อผู้ใช้</td></tr>{% endif %}
          {% if result.status == 'lastname-missing' %}<tr class="error"><td>{{forloop.counter}}</td><td class="user">{{result.email}}</td><td></td><td>ขาดข้อมูลนามสกุลผู้ใช้</td></tr>{% endif %}
          {% if result.status == 'section-invalid' %}<tr class="error"><td>{{forloop.counter}}</td><td class="user">{{result.email}}</td><td></td><td>รหัสสำนักไม่ถูกต้อง</td></tr>{% endif %}
          
          {% if result.status == 'duplicated' %}<tr><td>{{forloop.counter}}</td><td class="user">{{result.user.email}} ({{result.user.get_profile.get_fullname}})</td><td>{{result.user.get_profile.primary_role.name}}</td><td>มีชื่อผู้ใช้นี้อยู่ในระบบแล้ว</td></tr>{% endif %}

        {% if result.status == 'success' or result.status == 'success-duplicated' %}

          <tr>
            <td>{{forloop.counter}}</td>
            <td class="user">{{result.user.get_profile.email}} ({{result.user.get_profile.get_fullname}})</td>
            <td>{{result.user.get_profile.primary_role.name}}</td>
            <td>{% if result.status == 'success' %}สร้างผู้ใช้เรียบร้อย{% else %}มีชื่อผู้ใช้นี้อยู่ในระบบแล้ว{% endif %}</td>
          </tr>

          {% if result.project_result %}
            {% for project_result in result.project_result %}
              {% if project_result.status == 'project-invalid' %}<tr class="error"><td></td><td colspan="3">รหัสโครงการ {{project_result.project_ref_no_str}} ไม่ถูกต้อง</td></tr>{% endif %}
              {% if project_result.status == 'duplicated' %}<tr><td></td><td colspan="3">ผู้ใช้รับผิดชอบโครงการ <span title="{{project_result.project.name}}">{{project_result.project.ref_no}}</span> อยู่แล้ว</td></tr>{% endif %}
              {% if project_result.status == 'success' %}<tr><td></td><td colspan="3">เพิ่มโครงการ <span title="{{project_result.project.name}}">{{project_result.project.ref_no}}</span> เป็นโครงการที่รับผิดชอบเรียบร้อย</td></tr>{% endif %}
            {% endfor %}
          {% endif %}

        {% endif %}

        {% endfor %}
      </tbody>
    </table>

  {% endif %}  
</div>
{% endblock %}