domain/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('domain.views',

    url(r'^organization/$', 'view_organization', name='view_organization'),

    url(r'^section/(?P<section_ref_no>\d+)/$', 'view_section', name='view_section'),
    url(r'^section/(?P<section_ref_no>\d+)/projects/$', 'view_section_projects', name='view_section_projects'),
    url(r'^section/(?P<section_ref_no>\d+)/projects/(?P<year>\d+)/$', 'view_section_projects_in_year', name='view_section_projects_in_year'),

    url(r'^project/(?P<project_ref_no>\w+)/$', 'view_project', name='view_project'),
    url(r'^project/(?P<project_ref_no>\w+)/activity/$', 'view_project_activity', name='view_project_activity'),
    url(r'^project/(?P<project_ref_no>\w+)/edit/$', 'edit_project', name='edit_project'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('accounts.urls')),
    url(r'^', include('budget.urls')),
    url(r'^', include('domain.urls')),
    url(r'^', include('management.urls')),
    url(r'^', include('report.urls')),

    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page':'/accounts/login/'},name='auth_logout'),
    url(r'^accounts/password_reset/$', 'django.contrib.auth.views.password_reset', name='auth_password_reset'),
    url(r'^accounts/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='auth_password_reset_done'),
    url(r'^accounts/reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', name='auth_password_reset_confirm'),
    url(r'^accounts/reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='auth_password_reset_complete'),

    (r'^$', RedirectView.as_view(url='dashboard/')),

    url(r'^admin/', include(admin.site.urls)),
)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

domain/models.py
# -*- encoding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models

from accounts.models import ProjectManager

class Section(models.Model):
    ref_no = models.CharField(max_length=10)
    prefix = models.CharField(max_length=50)
    name = models.CharField(max_length=500)
    long_abbr_name = models.CharField(max_length=100)
    short_abbr_name = models.CharField(max_length=100)
    order_number = models.IntegerField(default=0)

    def __unicode__(self):
        return self.short_abbr_name

class Project(models.Model):
    section = models.ForeignKey(Section)
    ref_no = models.CharField(max_length=100, unique=True)
    contract_no = models.CharField(max_length=100, null=True, unique=True)
    prefix = models.CharField(max_length=50, blank=True)
    name = models.CharField(max_length=1000)
    abbr_name = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    manager_name = models.CharField(max_length=300, blank=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    project_type = models.IntegerField(default=0) # Not use yet
    status = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User)

    class Meta:
        ordering = ['ref_no']
    
    def __unicode__(self):
        return self.ref_no
    
    def is_active(self):
        return self.status in (u'อนุมัติ', u'รอปิดโครงการ')

    def managers(self):
        return ProjectManager.objects.filter(project=self, is_active=True)

## IMPORT FROM GMS ##

class ImportGMS(models.Model):
    started = models.DateTimeField(auto_now_add=True)
    finished = models.DateTimeField()
    imported_by = models.ForeignKey(User)
    created_projects = models.IntegerField(default=0)
    updated_projects = models.IntegerField(default=0)
    notfound_projects = models.IntegerField(default=0)
    created_budgets = models.IntegerField(default=0)

class ImportGMSProjects(models.Model):
    job = models.ForeignKey(ImportGMS)
    project_ref_no = models.CharField(max_length=100)
    is_found = models.BooleanField()
    is_created = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)

domain/forms.py
# -*- encoding: utf-8 -*-

from django import forms

from common.forms import StrippedCharField

from domain.models import Section

class AddUserForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'span6'}))
    firstname = StrippedCharField(max_length=300, widget=forms.TextInput(attrs={'class':'span5'}))
    lastname = StrippedCharField(max_length=300, widget=forms.TextInput(attrs={'class':'span5'}))
    primary_role = forms.ChoiceField(choices=(('section_manager', 'ผู้อำนวยการสำนัก'), ('section_assistant', 'ผู้ประสานงานสำนัก'), ('project_manager', 'ผู้จัดการแผนงาน')))

class AddSectionUserResponsibilityForm(forms.Form):
    sections = forms.ModelMultipleChoiceField(queryset=Section.objects.all(), widget=forms.CheckboxSelectMultiple())

class AddProjectManagerResponsibilityForm(forms.Form):
    project_ref_no = StrippedCharField(max_length=100, widget=forms.TextInput(attrs={'class':'span5'}))

class ImportUserForm(forms.Form):
    user_csv = forms.FileField()

domain/views.py
# -*- encoding: utf-8 -*-

import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render

from common.utilities import make_random_user_password

from accounts.models import UserProfile, UserSection, ProjectManager

from models import *

@login_required
def view_organization(request):
    sections = Section.objects.all().order_by('order_number')
    return render(request, 'domain/organization.html', {'sections':sections})

## SECTION PAGE ##

@login_required
def view_section(request, section_ref_no):
    section = get_object_or_404(Section, ref_no=section_ref_no)
    
    today = datetime.date.today()
    current_projects = Project.objects.filter(section=section, status__in=('อนุมัติ', 'รอปิดโครงการ')).order_by('-ref_no')
    
    return render(request, 'domain/section_overview.html', {'section':section, 'current_projects':current_projects})

@login_required
def view_section_projects(request, section_ref_no):
    year = datetime.date.today().year
    return _section_projects_in_year(request, section_ref_no, year)

@login_required
def view_section_projects_in_year(request, section_ref_no, year):
    year = int(year) - 543
    return _section_projects_in_year(request, section_ref_no, year)

def _section_projects_in_year(request, section_ref_no, year):
    section = get_object_or_404(Section, ref_no=section_ref_no)
    projects = Project.objects.filter(section=section, ref_no__startswith=str(year+543)[2:4]).order_by('ref_no')

    this_year = datetime.date.today().year
    years = range(this_year, this_year-10, -1)
    return render(request, 'domain/section_projects.html', {'section': section, 'projects':projects, 'showing_year':year, 'all_years':years})

## PROJECT ##

@login_required
def view_project(request, project_ref_no):
    project = get_object_or_404(Project, ref_no=project_ref_no)
    if request.user.get_profile().is_manage_project(project):
        return redirect('view_project_outstanding_reports', project_ref_no=project_ref_no)
    else:    
        return redirect('view_project_reports', project_ref_no=project_ref_no)

@login_required
def view_project_activity(request, project_ref_no):
    project = get_object_or_404(Project, ref_no=project_ref_no)

    return render(request, 'domain/project_activity.html', {'project': project, })

@login_required
def edit_project(request, project_ref_no):
    project = get_object_or_404(Project, ref_no=project_ref_no)

    return render(request, 'domain/project_edit.html', {'project': project, })

templates/domain/admin/manage_import.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}ดึงข้อมูลจาก GMS{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'domain/admin/snippets/admin_tabs.html' with active_menu='import' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <form method="POST" action=".">
    {% csrf_token %}
    <div class="page_actions"><button type="submit" class="primary btn">เริ่มต้นดึงข้อมูล</button></div>
  </form>

    <div class="last_import">
        <h2>ผลลัพธ์การดึงข้อมูลครั้งล่าสุด</h2>
        <ul>
            <li>สร้างโครงการ 10 โครงการ</li>
        </ul>
        <div class="view_details"><a href="{% url view_manage_import_details %}">ดูผลลัพธ์อย่างละเอียด</a></div>
    </div>


</div>
{% endblock %}

templates/domain/admin/manage_users.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}จัดการผู้ใช้{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'domain/admin/snippets/admin_tabs.html' with active_menu='user' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
    <div class="page_actions"><a href="{% url view_manage_users_add %}" class="btn">เพิ่มผู้ใช้ระบบ</a></div>

    {% include 'domain/admin/snippets/admin_users_tabs.html' %}

    <table class="bordered-table zebra-striped">
      <colgroup>
        <col width=""/>
        <col width="150px"/>
        <col width="300px"/>
        <col width="80px"/>
      </colgroup>
      <thead>
        <tr>
          <th>ชื่อ</th>
          <th>สำนัก</th>
          <th>ประเภทผู้ใช้</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Panu Tangchalermkul</td>
          <td>สำนัก 7</td>
          <td>บางตำแหน่ง</td>
          <td><a href="#" class="small btn">แก้ไข</a></td>
        </tr>
        <tr>
          <td>Panu Tangchalermkul</td>
          <td>สำนัก 7</td>
          <td>บางตำแหน่ง</td>
          <td><a href="#" class="small btn">แก้ไข</a></td>
        </tr>
        <tr>
          <td>Panu Tangchalermkul</td>
          <td>สำนัก 7</td>
          <td>บางตำแหน่ง</td>
          <td><a href="#" class="small btn">แก้ไข</a></td>
        </tr>
        
      </tbody>
    </table>





</div>
{% endblock %}

templates/domain/admin/manage_users_add.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}เพิ่มผู้ใช้ระบบ{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'domain/admin/snippets/admin_tabs.html' with active_menu='user' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_manage_users %}">จัดการผู้ใช้</a> <span class="divider">/</span></li>
    <li class="active">เพิ่มผู้ใช้ระบบ</li>
  </ul>
  <h2>เพิ่มผู้ใช้ระบบ</h2>

  <ul class="tabs">
    <li class="active"><a href="{% url view_manage_users_add %}">กรอกจากแบบฟอร์ม</a></li>
    <li><a href="{% url view_manage_users_import %}">ดึงจากไฟล์ CSV</a></li>
  </ul>

  <form method="POST" action=".">
    {% csrf_token %}
    {{form.non_field_errors}}

    <div class="clearfix"><label for="id_email">อีเมล</label><div class="input">{{form.email}}{{form.email.errors}}<div class="help-block">* ใช้สำหรับการเข้าสู่ระบบ และการแจ้งเตือนต่างๆ</div></div></div>
    <div class="clearfix"><label for="id_firstname">ชื่อ</label><div class="input">{{form.firstname}}{{form.firstname.errors}}</div></div>
    <div class="clearfix"><label for="id_lastname">นามสกุล</label><div class="input">{{form.lastname}}{{form.lastname.errors}}</div></div>
    <div class="clearfix"><label for="id_primary_role">ประเภทผู้ใช้</label><div class="input">{{form.primary_role}}{{form.primary_role.errors}}</div></div>

    <div class="form_actions">
      <button type="submit" class="btn primary">บันทึกและไปขั้นตอนต่อไป</button>
      <button type="reset" class="btn">ล้างข้อมูล</button>
    </div>
  </form>


</div>
{% endblock %}

templates/domain/admin/manage_users_add_project_manager.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}เพิ่มผู้ใช้ระบบ{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'domain/admin/snippets/admin_tabs.html' with active_menu='user' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_manage_users %}">จัดการผู้ใช้</a> <span class="divider">/</span></li>
    <li class="active">เพิ่มผู้ใช้ระบบ</li>
  </ul>
  <h2>ใส่ข้อมูลหน่วยงาน</h2>

  <form method="POST" action=".">
    {% csrf_token %}
    {{form.non_field_errors}}

    <div class="clearfix"><label for="id_project_ref_no">รหัสโครงการ</label><div class="input">{{form.project_ref_no}}{{form.project_ref_no.errors}}</div></div>
    
    <div class="form_actions">
      <button type="submit" class="btn primary" name="submit_continue_button">บันทึกข้อมูล และกลับมาหน้านี้</button>
      <button type="submit" class="btn primary" name="submit_button">บันทึกข้อมูล</button>
      <button type="reset" class="btn">ล้างข้อมูล</button>
    </div>
  </form>
</div>
{% endblock %}

templates/domain/admin/manage_users_add_section_user.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}เพิ่มผู้ใช้ระบบ{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'domain/admin/snippets/admin_tabs.html' with active_menu='user' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_manage_users %}">จัดการผู้ใช้</a> <span class="divider">/</span></li>
    <li class="active">เพิ่มผู้ใช้ระบบ</li>
  </ul>

  <h2>ใส่ข้อมูลหน่วยงาน</h2>

  <form method="POST" action=".">
    {% csrf_token %}
    {{form.non_field_errors}}

    <div class="clearfix"><label for="id_sections">สำนักที่สังกัด</label><div class="input row-inputs">{{form.sections}}{{form.sections.errors}}</div></div>
    
    <div class="form_actions">
      <button type="submit" class="btn primary">เพิ่มผู้ใช้ระบบ</button>
      <button type="reset" class="btn">ล้างข้อมูล</button>
    </div>
  </form>
</div>
{% endblock %}

templates/domain/admin/manage_users_import.html
{% extends 'base_authenticated.html' %}

{% block head_title %}{{block.super}}เพิ่มผู้ใช้ระบบ{% endblock %}

{% block body_title %}<div class="title"><h1>การจัดการระบบ</h1></div>{% endblock %}

{% block body_tabs %}{% include 'domain/admin/snippets/admin_tabs.html' with active_menu='user' %}{% endblock %}

{% block body_content %}
<div class="admin_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_manage_users %}">จัดการผู้ใช้</a> <span class="divider">/</span></li>
    <li class="active">เพิ่มผู้ใช้ระบบ</li>
  </ul>
  <h2>เพิ่มผู้ใช้ระบบ</h2>

  <ul class="tabs">
    <li><a href="{% url view_manage_users_add %}">กรอกฟอร์มผู้ใช้</a></li>
    <li class="active"><a href="{% url view_manage_users_import %}">ดึงจากไฟล์ CSV</a></li>
  </ul>

  <form method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{form.non_field_errors}}

    <div class="clearfix">
      <label for="id_user_csv">ไฟล์ CSV</label>
      <div class="input">{{form.user_csv}}{{form.user_csv.errors}}</div>
    </div>

    <div class="form_actions">
      <button type="submit" class="btn primary">เพิ่มผู้ใช้ระบบ</button>
      <button type="reset" class="btn">ล้างข้อมูล</button>
    </div>
  </form>

  <div class="user_import_guide">
    <h3>วิธีการสร้างไฟล์ CSV</h3>

    <ol>
      <li>สร้างไฟล์ Excel ที่มีข้อมูลผู้ใช้ดังรูป</li>
    </ol>

  </div>
</div>
{% endblock %}