report/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('report.views',
    url(r'^project/(?P<project_ref_no>\w+)/reports/$', 'view_project_reports', name='view_project_reports'),
    
    url(r'^project/(?P<project_ref_no>\w+)/reports/outstanding/$', 'view_project_outstanding_reports', name='view_project_outstanding_reports'),
    url(r'^project/(?P<project_ref_no>\w+)/reports/recent/$', 'view_project_recent_reports', name='view_project_recent_reports'),
    url(r'^project/(?P<project_ref_no>\w+)/reports/all/$', 'view_project_all_reports', name='view_project_all_reports'),
    url(r'^project/(?P<project_ref_no>\w+)/report/(?P<report_id>\d+)/$', 'view_project_report', name='view_project_report'),

    url(r'^project/(?P<project_ref_no>\d+)/report/(?P<report_id>\d+)/(?P<schedule_date>\w+)/$', 'view_report', name='view_report'),
    url(r'^project/(?P<project_ref_no>\d+)/report/(?P<report_id>\d+)/(?P<schedule_date>\w+)/submit/$', 'submit_project_report', name='submit_project_report'),
    url(r'^project/(?P<project_ref_no>\d+)/report/(?P<report_id>\d+)/(?P<schedule_date>\w+)/submit-text/$', 'submit_project_report_text', name='submit_project_report_text'),
    url(r'^project/(?P<project_ref_no>\d+)/report/(?P<report_id>\d+)/(?P<schedule_date>\w+)/submit-attachment/$', 'submit_project_report_attachment', name='submit_project_report_attachment'),

    url(r'^report/attachment/download/(?P<uid>[a-zA-Z0-9\-]+)/$', 'download_report_attachment', name='download_report_attachment'),
    url(r'^report/attachment/delete/(?P<uid>[a-zA-Z0-9\-]+)/$', 'delete_report_attachment', name='delete_report_attachment'),

)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('accounts.urls')),
    url(r'^', include('budget.urls')),
    url(r'^', include('domain.urls')),
    url(r'^', include('management.urls')),
    url(r'^', include('report.urls')),

    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page':'/accounts/login/'},name='auth_logout'),
    url(r'^accounts/password_reset/$', 'django.contrib.auth.views.password_reset', name='auth_password_reset'),
    url(r'^accounts/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='auth_password_reset_done'),
    url(r'^accounts/reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', name='auth_password_reset_confirm'),
    url(r'^accounts/reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='auth_password_reset_complete'),

    (r'^$', RedirectView.as_view(url='dashboard/')),

    url(r'^admin/', include(admin.site.urls)),
)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

report/forms.py
# -*- encoding: utf-8 -*-

from django import forms

from common.forms import StrippedCharField

class SubmitReportTextForm(forms.Form):
    report_text = StrippedCharField(required=False)

class SubmitReportAttachmentForm(forms.Form):
    report_attachment = forms.FileField()

report/views.py
# -*- encoding: utf-8 -*-

import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render

from http import Http403

from private_files.views import get_file as private_files_get_file

from common.utilities import convert_dateid_to_date, format_dateid, split_filename

from domain.models import Section, Project

from forms import *
from models import *

@login_required
def view_project_reports(request, project_ref_no): # DONE
    project = get_object_or_404(Project, ref_no=project_ref_no)

    if request.user.get_profile().is_manage_project(project):
        return redirect('view_project_outstanding_reports', project_ref_no=project_ref_no)
    else:
        return redirect('view_project_recent_reports', project_ref_no=project_ref_no)

@login_required
def view_project_outstanding_reports(request, project_ref_no): # DONE
    project = get_object_or_404(Project, ref_no=project_ref_no)

    if request.user.get_profile().is_manage_project(project):
        report_assignments = []

        if project.is_active():
            for report_assignment in ReportAssignment.objects.filter(project=project):
                report_assignment.outstanding_schedules = report_assignment.get_outstanding_schedules()
                
                if report_assignment.outstanding_schedules:
                    report_assignments.append(report_assignment)

        return render(request, 'domain/project_reports_outstanding.html', {'project': project, 'report_assignments':report_assignments})
    
    else:
        raise Http404

@login_required
def view_project_recent_reports(request, project_ref_no): # DONE
    project = get_object_or_404(Project, ref_no=project_ref_no)
    submissions = ReportSubmission.objects.filter(project=project).exclude(submitted_on=None).order_by('-submitted_on')[:20]
    return render(request, 'domain/project_reports_recent.html', {'project': project, 'submissions':submissions})

@login_required
def view_project_all_reports(request, project_ref_no):
    project = get_object_or_404(Project, ref_no=project_ref_no)
    report_assignments = ReportAssignment.objects.filter(project=project).order_by('report__name')
    return render(request, 'domain/project_reports.html', {'project': project, 'report_assignments':report_assignments})

@login_required
def view_project_report(request, project_ref_no, report_id):
    project = get_object_or_404(Project, ref_no=project_ref_no)
    report = get_object_or_404(Report, pk=report_id)

    submissions = []

    if project.is_active():
        schedule_dates = report.get_schedules_until(and_one_beyond=True)
        
        for schedule_date in schedule_dates:
            try:
                submission = ReportSubmission.objects.get(report=report, project=project, schedule_date=schedule_date)
            except:
                submission = ReportSubmission(report=report, project=project, schedule_date=schedule_date)
            
            if not request.user.get_profile().is_manage_project(project):
                if submission.submitted_on:
                    submissions.append(submission)

            else:
                submissions.append(submission)

        for submission in ReportSubmission.objects.filter(project=project, report=report).exclude(submitted_on=None):
            if not submission.schedule_date in schedule_dates:
                submissions.append(submission)

        submissions.sort(key=lambda item:item.schedule_date, reverse=True)
    
    else:
        if request.user.get_profile().is_manage_project(project, role='pm'):
            submissions = ReportSubmission.objects.filter(project=project, report=report).order_by('-schedule_date')
        else:
            submissions = ReportSubmission.objects.filter(project=project, report=report).exclude(submitted_on=None).order_by('-schedule_date')

    return render(request, 'domain/project_report.html', {'project': project, 'report':report, 'submissions':submissions})

@login_required
def view_report(request, project_ref_no, report_id, schedule_date):
    project = get_object_or_404(Project, ref_no=project_ref_no)
    report = get_object_or_404(Report, pk=report_id)
    schedule_date = convert_dateid_to_date(schedule_date)

    if not report.is_valid_schedule(schedule_date):
        print 'invalid schedule'
        raise Http404
    
    try:
        submission = ReportSubmission.objects.get(project=project, report=report, schedule_date=schedule_date)

        if not submission.submitted_on and not request.user.get_profile().is_manage_project(project, role='pm'):
            submission.attachments = []
        else:
            submission.attachments = ReportSubmissionAttachment.objects.filter(submission=submission).order_by('-uploaded')
    
    except:
        submission = ReportSubmission(project=project, report=report, schedule_date=schedule_date)
        submission.attachments = []
    
    if not project.is_active() and not submission.submitted_on and not request.user.get_profile().is_manage_project(project, role='pm'):
        raise Http404

    if not submission.submitted_on and not request.user.get_profile().is_manage_project(project):
        raise Http404
    
    if not submission.submitted_on and not request.user.get_profile().is_manage_project(project, role='pm'):
        submission.report_text = '' # not allow other people to see unfinished report
    
    return render(request, 'report/report_overview.html', {'project':project, 'report':report, 'submission':submission})

@login_required
def submit_project_report(request, project_ref_no, report_id, schedule_date):
    if request.method == 'POST':
        project = get_object_or_404(Project, ref_no=project_ref_no)
        report = get_object_or_404(Report, pk=report_id)
        schedule_date = convert_dateid_to_date(schedule_date)

        if not request.user.get_profile().is_manage_project(project):
            raise Http403
        
        if not report.is_valid_schedule(schedule_date):
            raise Http404

        try:
            submission = ReportSubmission.objects.get(project=project, report=report, schedule_date=schedule_date)
            submission.submitted_on = datetime.datetime.now()
            submission.save()
            messages.success(request, u'ส่งรายงานเรียบร้อย')
        except ReportSubmission.DoesNotExist:
            messages.error(request, u'รายงานยังไม่มีเนื้อหา ไม่สามารถส่งได้')
        
        return redirect('view_report', project_ref_no=project_ref_no, report_id=report_id, schedule_date=format_dateid(schedule_date))
    
    else:
        raise Http404

@login_required
def submit_project_report_text(request, project_ref_no, report_id, schedule_date):
    if request.method == 'POST':
        project = get_object_or_404(Project, ref_no=project_ref_no)
        report = get_object_or_404(Report, pk=report_id)
        schedule_date = convert_dateid_to_date(schedule_date)

        if not request.user.get_profile().is_manage_project(project):
            raise Http403
        
        if not report.is_valid_schedule(schedule_date):
            raise Http404
        
        form = SubmitReportTextForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['report_text']

            try:
                submission = ReportSubmission.objects.get(project=project, report=report, schedule_date=schedule_date)
                submission.report_text = text
                submission.save()
            except ReportSubmission.DoesNotExist:
                submission = ReportSubmission.objects.create(project=project, report=report, schedule_date=schedule_date, report_text=text, created_by=request.user)
            
            messages.success(request, u'แก้ไขเนื้อหารายงานเรียบร้อย')
            
        else:
            messages.error(request, u'เนื้อหารายงานไม่อยู่ในรูปแบบที่ถูกต้อง')
            
        return redirect('view_report', project_ref_no=project_ref_no, report_id=report_id, schedule_date=format_dateid(schedule_date))
        
    else:
        raise Http404

@login_required
def submit_project_report_attachment(request, project_ref_no, report_id, schedule_date):
    if request.method == 'POST':
        project = get_object_or_404(Project, ref_no=project_ref_no)
        report = get_object_or_404(Report, pk=report_id)
        schedule_date = convert_dateid_to_date(schedule_date)

        if not request.user.get_profile().is_manage_project(project):
            raise Http403

        if not report.is_valid_schedule(schedule_date):
            raise Http404
        
        try:
            submission = ReportSubmission.objects.get(project=project, report=report, schedule_date=schedule_date)
        except ReportSubmission.DoesNotExist:
            submission = ReportSubmission(project=project, report=report, schedule_date=schedule_date)

        form = SubmitReportAttachmentForm(request.POST, request.FILES)
        if form.is_valid():
            file_attachment = form.cleaned_data['report_attachment']

            if not submission.id:
                submission.created_by = request.user
                submission.save()
            
            (file_name, file_ext) = split_filename(file_attachment.name)
            attachment = ReportSubmissionAttachment.objects.create(submission=submission, file_name=file_name, file_ext=file_ext, attachment=file_attachment, uploaded_by=request.user)

            messages.success(request, u'เพิ่มไฟล์แนบเรียบร้อย')

        else:
            return render(request, 'report/report_overview.html', {'project':project, 'report':report, 'submission':submission, 'attachment_form':form})
            

templates/report/report_delete_attachment.html
{% extends 'base_authenticated.html' %}
{% load page_tags %}

{% block head_title %}{{block.super}}รายงาน {{report.name}} งวดวันที่ {{submission.schedule_date|format_abbr_date}}{% endblock %}

{% block body_title %}{% include 'domain/snippets/project_header.html' %}{% endblock %}
{% block body_tabs %}{% include 'domain/snippets/project_tabs.html' with active_menu='report' %}{% endblock %}

{% block body_content %}
<div class="report_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_project_all_reports project.ref_no %}">รายงานทั้งหมด</a> <span class="divider">/</span></li>
    <li><a href="{% url view_project_report project.ref_no report.id %}">{{report.name}}</a> <span class="divider">/</span></li>
    <li class="active">งวดวันที่ {{submission.schedule_date|format_abbr_date}}</li>
  </ul>

  <h2>{{report.name}}<div class="subtitle">งวดวันที่ {{submission.schedule_date|format_abbr_date}}</div></h2>

  <form method="post" action=".">
    {% csrf_token %}
    <div class="note">กดปุ่มเพื่อยืนยันการลบไฟล์ {{attachment.file_name}}{% if attachment.file_ext %}.{{attachment.file_ext}}{% endif %}</div>

    <div class="form_actions left_form_actions">
      <button type="submit" name="submit-delete" class="btn btn-danger">ยืนยันการลบไฟล์แนบ</button>
      <button type="submit" name="submit-cancel" class="btn">ยกเลิก</button>
    </div>
  </form>

</div>
{% endblock %}

templates/report/report_overview.html
{% extends 'base_authenticated.html' %}
{% load page_tags %}

{% block head_title %}{{block.super}}รายงาน {{report.name}} งวดวันที่ {{submission.schedule_date|format_abbr_date}}{% endblock %}

{% block html_head %}
{{block.super}}
{% manage user project 'pm' %}
<script type="text/javascript" src="{{STATIC_URL}}libs/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}libs//ckeditor/adapters/jquery.js"></script>
<script>
var initializedTextarea = false;
$(document).ready(function() {
  $('.edit_report_button').on('click', function(e) {
    if(initializedTextarea == false) {
      var config = {
        toolbar:[['Bold', 'Italic', 'Underline', '-', 'NumberedList', 'BulletedList'],],
        language:'th'
      };
      $('.report_text_editor textarea').ckeditor(config);

      CKEDITOR.on( 'instanceReady', function( ev ) {
        ev.editor.dataProcessor.writer.setRules( 'p', {
          indent : false,
          breakBeforeOpen : true,
          breakAfterOpen : false,
          breakBeforeClose : false,
          breakAfterClose : true
        });
      });

      $('.report_text_editor button[type="button"]').on('click', function(e) {
        $('.report_text_editor').hide();
        $('.report_text').show();
        $('.report_actions').show();
      });
    }

    $('.report_text_editor').show();
    $('.report_text').hide();
    $('.report_actions').hide();

    return false;
  });

  $('.attach_report_button').on('click', function(e) {
    $('#report_attachment_form input[type="file"]').click();
    return false;
  });

  $('#report_attachment_form input[type="file"]').on('change', function(e) {
      $('#report_attachment_form').submit();
  });

});
</script>
{% endmanage %}
{% endblock %}

{% block body_title %}{% include 'domain/snippets/project_header.html' %}{% endblock %}
{% block body_tabs %}{% include 'domain/snippets/project_tabs.html' with active_menu='report' %}{% endblock %}

{% block body_content %}
<div class="report_page">
  <ul class="breadcrumb">
    <li><a href="{% url view_project_all_reports project.ref_no %}">รายงานทั้งหมด</a> <span class="divider">/</span></li>
    <li><a href="{% url view_project_report project.ref_no report.id %}">{{report.name}}</a> <span class="divider">/</span></li>
    <li class="active">งวดวันที่ {{submission.schedule_date|format_abbr_date}}</li>
  </ul>

  <h2>{{report.name}}<div class="subtitle">งวดวันที่ {{submission.schedule_date|format_abbr_date}}{% if submission.submitted_on %}<div class="submitted">รายงานถูกส่งแล้วเมื่อวันที่ <em>{{submission.submitted_on|format_datetime}}</em></div>{% endif %}</div></h2>

  {% manage user project 'pm' %}
  <div class="report_actions">
    {% if not submission.submitted_on %}{% if submission.report_text or submission.attachments %}<form method="POST" action="{% url submit_project_report project.ref_no report.id submission.schedule_date|dateid %}">{% csrf_token %}<button type="submit" class="btn-primary submit btn">ส่งรายงาน</button></form>{% endif %}{% endif %}
    <a href="#" class="btn edit_report_button">{% if not submission.report_text %}เขียนเนื้อหารายงาน{% else %}แก้ไขเนื้อหารายงาน{% endif %}</a>
    <a href="#" class="btn attach_report_button">แนบไฟล์รายงาน</a>
  </div>
  {% endmanage %}

  {% if not submission.report_text and not submission.attachments %}<div class="no_information">ไม่มีเนื้อหารายงาน</div>{% endif %}

  {% if submission.report_text %}
  <div class="report_text">
    {{submission.report_text|safe}}
  </div>
  {% endif %}

  {% manage user project 'pm' %}
  <div class="report_text_editor" style="display:none;">
    <form method="post" action="{% url submit_project_report_text project.ref_no report.id submission.schedule_date|dateid %}">
      {% csrf_token %}
      <textarea name="report_text">{{submission.report_text|safe}}</textarea>
      <div class="button_panel"><button type="submit" class="btn-primary btn">จัดเก็บ</button><button type="button" class="btn">ยกเลิก</button></div>
    </form>
  </div>
  {% endmanage %}

  {% if submission.attachments %}
  <div class="report_attachment">
    <h3>ไฟล์แนบ</h3>
    <ul>
      {% for attachment in submission.attachments %}
      <li>
        <div class="filename"><a href="{% url download_report_attachment attachment.uid %}">{{attachment.file_name}}{% if attachment.file_ext %}.{{attachment.file_ext}}{% endif %}</a></div>
        <div class="metadata">อัพโหลดเมื่อวันที่ {{attachment.uploaded|format_abbr_datetime}} โดย {{attachment.uploaded_by.get_profile.get_fullname}}{% manage user project %} | <a href="{% url delete_report_attachment attachment.uid %}">ลบไฟล์แนบ</a>{% endmanage %}</div>
      </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  {% manage user project 'pm' %}
  <form method="post" id="report_attachment_form" action="{% url submit_project_report_attachment project.ref_no report.id submission.schedule_date|dateid %}" enctype="multipart/form-data" style="opacity:0;text-indent:-9999px;">
    {% csrf_token %}
    {{attachment_form.errors}}
    <input type="file" name="report_attachment" id="id_report_attachment"/>
  </form>
  {% endmanage %}

</div>
{% endblock %}

templates/report/section_reports.html
{% extends 'base_authenticated.html' %}
{% load page_tags %}

{% block body_title %}{% include 'domain/snippets/section_header.html' %}{% endblock %}
{% block body_tabs %}{% include 'domain/snippets/section_tabs.html' with active_menu='report' %}{% endblock %}

{% block body_content %}
<div class="section_page">
  <div class="page_actions"><a href="#" class="btn">สร้างหัวข้อรายงาน</a></div>

  <table>
    <colgroup>
      <col width="" />
      <col width="300" />
      <col width="230" />
      <col width="80" />
    </colgroup>
    <thead>
      <tr>
        <th>รายงาน</th>
        <th>กำหนดส่ง</th>
        <th>จำนวนโครงการที่ต้องส่ง</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Report Name</td>
        <td>ทุกวันที่ 15 ของทุกเดือน</td>
        <td>14</td>
        <td><a href="#" class="btn">แก้ไข</a></td>
      </tr>
      <tr>
        <td>Report Name</td>
        <td>ทุกวันที่ 15 ของทุกเดือน</td>
        <td>14</td>
        <td><a href="#" class="btn">แก้ไข</a></td>
      </tr>
    </tbody>
  </table>
    
</div>
{% endblock %}